"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Profile = { creator_slug: string; creator_headline: string; creator_bio: string; creator_public: boolean };
type Analytics = { totals: { views: number; shares: number; enrollments: number; started: number; completions: number; readerOpens: number }; courses: Array<Record<string, string | number>> };
export default function CreatorDashboard() {
  const [profile, setProfile] = useState<Profile | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/creator-profile"), fetch("/api/creator/analytics")]).then(async ([p, a]) => { if (p.status === 401) { location.href = "/login?next=/analytics"; return; } setProfile((await p.json()).profile); setAnalytics(await a.json()); }); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!profile) return; setMessage("Saving…"); const response = await fetch("/api/creator-profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug: profile.creator_slug, headline: profile.creator_headline, bio: profile.creator_bio, isPublic: profile.creator_public }) }); const data = await response.json(); if (response.ok) { setProfile(data.profile); setMessage("Profile saved"); } else setMessage(data.error); }
  if (!profile || !analytics) return <div className="h-64 rounded-[1.5rem] skeleton" />;
  const metrics = [["Page views", analytics.totals.views], ["Shares", analytics.totals.shares], ["Enrollments", analytics.totals.enrollments], ["Learners started", analytics.totals.started], ["Completions", analytics.totals.completions], ["Reader opens", analytics.totals.readerOpens]];
  return <div className="space-y-8"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{metrics.map(([label, value]) => <div key={String(label)} className="rounded-[1.3rem] border border-line bg-card p-5 shadow-card"><p className="text-xs font-semibold text-ink-soft">{label}</p><p className="display mt-2 text-4xl">{value}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-[1.5rem] border border-line bg-card p-6 shadow-card"><div className="flex items-end justify-between"><div><p className="section-label">Course performance</p><h2 className="display mt-2 text-4xl">What resonates.</h2></div></div>{analytics.courses.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs text-ink-soft"><tr><th className="pb-3">Course</th><th>Views</th><th>Shares</th><th>Enrollments</th><th>Started</th></tr></thead><tbody>{analytics.courses.map((course) => <tr key={Number(course.id)} className="border-t border-line"><td className="py-4 font-semibold">{course.title}</td><td>{course.views}</td><td>{course.shares}</td><td>{course.enrollments}</td><td>{course.started}</td></tr>)}</tbody></table></div> : <div className="mt-6 rounded-xl bg-paper p-8 text-center"><p className="font-semibold">Create your first course to begin learning what works.</p><Link href="/create" className="mt-4 inline-flex rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white">Create a course</Link></div>}</div>
    <form onSubmit={save} className="rounded-[1.5rem] border border-line bg-card p-6 shadow-card"><p className="section-label">Public creator profile</p><h2 className="display mt-2 text-4xl">Your corner of BookQuest.</h2><label className="mt-6 block text-xs font-bold">Profile address<input className="field mt-2" value={profile.creator_slug} onChange={(e) => setProfile({ ...profile, creator_slug: e.target.value })} /></label><label className="mt-4 block text-xs font-bold">Headline<input className="field mt-2" maxLength={120} value={profile.creator_headline} onChange={(e) => setProfile({ ...profile, creator_headline: e.target.value })} /></label><label className="mt-4 block text-xs font-bold">About<textarea className="field mt-2 min-h-28" maxLength={600} value={profile.creator_bio} onChange={(e) => setProfile({ ...profile, creator_bio: e.target.value })} /></label><label className="mt-4 flex gap-3 text-sm"><input type="checkbox" checked={profile.creator_public} onChange={(e) => setProfile({ ...profile, creator_public: e.target.checked })} /> Make my creator page public</label><button className="btn-primary mt-6 w-full">Save profile</button>{message && <p className="mt-3 text-sm text-ink-soft" aria-live="polite">{message}</p>}{profile.creator_public && <Link className="mt-3 block text-center text-sm font-semibold text-teal" href={`/creator/${profile.creator_slug}`}>View public profile</Link>}</form></section></div>;
}
