import type { Card } from "@/lib/schemas";
import AppIcon from "@/components/AppIcon";

export type RichCard = Exclude<Card, { type: "concept" | "example" | "recap" | "quiz_mcq" | "quiz_truefalse" | "quiz_fillblank" }>;

export default function RichBlockCard({ card }: { card: RichCard }) {
  if (card.type === "image") return <figure className="overflow-hidden rounded-[1.5rem] border border-line bg-card shadow-card"><img src={card.url} alt={card.decorative ? "" : card.altText} loading="lazy" decoding="async" className="max-h-[70dvh] w-full object-contain" />{card.caption && <figcaption className="border-t border-line px-5 py-4 text-sm leading-6 text-ink-soft">{card.caption}</figcaption>}</figure>;

  if (card.type === "audio_video") return <article className="overflow-hidden rounded-[1.6rem] bg-pine text-white shadow-pop"><div className="relative px-6 py-10 text-center sm:px-10 sm:py-14"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full border border-signal/35 bg-signal/10 text-signal"><AppIcon name="compass" className="h-6 w-6" /></span><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.16em] text-signal">Media stage</p><h2 className="display mt-2 text-4xl leading-none sm:text-5xl">{card.title}</h2><a href={card.url} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-signal px-6 py-3 text-sm font-bold text-ink">Open media <AppIcon name="arrow" className="h-4 w-4" /></a></div>{(card.transcript || card.captions) && <details className="border-t border-white/10 bg-white/5 px-6 py-5"><summary className="text-sm font-semibold text-white">Read {card.transcript ? "transcript" : "captions"}</summary><p className="reading mt-4 whitespace-pre-wrap text-white/75">{card.transcript || card.captions}</p></details>}</article>;

  if (card.type === "story") return <article className="relative overflow-hidden rounded-[1.6rem] border border-amber/30 bg-[linear-gradient(145deg,#fffaf0,#f4ead8)] p-6 shadow-card sm:p-10"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-amber/15 blur-3xl" aria-hidden="true" /><p className="relative text-[10px] font-bold uppercase tracking-[0.17em] text-rose">Story</p><h2 className="display relative mt-4 text-[clamp(2.6rem,9vw,4.4rem)] leading-[0.92]">{card.title}</h2><p className="reading relative mt-7 whitespace-pre-wrap font-[450]">{card.body}</p></article>;

  if (card.type === "flashcard") return <article className="space-y-4" aria-label="Flashcard"><div className="relative min-h-56 overflow-hidden rounded-[1.6rem] border border-line bg-ivory p-7 shadow-card sm:p-10"><span className="absolute right-5 top-5 grid h-9 w-9 place-items-center rounded-full bg-sky text-dusk"><AppIcon name="bookmark" className="h-4 w-4" /></span><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-ink-soft">{card.frontLabel}</p><h2 className="display mt-8 max-w-xl text-4xl leading-[1.02]">{card.front}</h2></div><details className="rounded-[1.6rem] border border-teal/30 bg-teal/8 p-6 shadow-card open:bg-go-soft/60 sm:p-8"><summary className="flex min-h-11 items-center justify-between gap-4 font-semibold"><span>Reveal {card.backLabel}</span><span className="grid h-8 w-8 place-items-center rounded-full bg-teal text-white" aria-hidden="true">+</span></summary><p className="reading mt-5 border-t border-teal/20 pt-5">{card.back}</p></details></article>;

  if (card.type === "scenario") return <article className="overflow-hidden rounded-[1.6rem] border border-dusk/25 bg-card shadow-card"><div className="bg-dusk px-6 py-6 text-white sm:px-9"><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-white/65">Decision point</p><p className="reading mt-4 text-white">{card.context}</p></div><div className="p-6 sm:p-9"><h2 className="display text-3xl leading-none sm:text-4xl">{card.decisionPrompt}</h2>{card.options && <ol className="mt-6 space-y-3">{card.options.map((option, index) => <li key={option} className="flex gap-3 rounded-xl border border-line bg-paper/55 p-4 text-sm leading-6"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-dusk text-xs font-bold text-white">{index + 1}</span>{option}</li>)}</ol>}{card.guidance && <details className="mt-6 rounded-xl bg-sky/45 p-4"><summary className="font-semibold">Consider the guidance</summary><p className="mt-3 text-sm leading-6 text-ink-soft">{card.guidance}</p></details>}</div></article>;

  if (card.type === "practical_task") return <article className="rounded-[1.6rem] border border-amber/40 bg-[linear-gradient(145deg,#fff9eb,#f5e6c6)] p-6 shadow-card sm:p-9"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-amber text-ink"><AppIcon name="trail" className="h-5 w-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-ink-soft">Mission briefing</p><h2 className="display mt-2 text-4xl leading-none">{card.title}</h2></div></div><ol className="mt-7 space-y-4">{card.instructions.map((step, index) => <li key={step} className="flex gap-4 border-t border-amber/25 pt-4 text-sm leading-6"><span className="font-display text-2xl text-rose">{String(index + 1).padStart(2, "0")}</span><span>{step}</span></li>)}</ol><div className="mt-7 rounded-xl border border-amber/30 bg-ivory/70 p-4 text-sm leading-6"><strong className="block text-[10px] uppercase tracking-[0.15em] text-ink-soft">Accessible alternative</strong><span className="mt-1 block">{card.submissionAlternative}</span></div></article>;

  if (card.type === "discussion") return <article className="rounded-[1.6rem] border border-moss/30 bg-forest p-6 text-white shadow-pop sm:p-9"><span className="grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-white/5 text-signal"><AppIcon name="people" className="h-5 w-5" /></span><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.17em] text-signal">Roundtable</p><h2 className="display mt-3 text-[clamp(2.5rem,9vw,4.2rem)] leading-[0.94]">{card.prompt}</h2><p className="mt-7 rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-white/70"><strong className="block text-white">Prefer to reflect privately?</strong>{card.privateAlternative}</p></article>;

  if (card.type === "survey") return <form className="rounded-[1.6rem] border border-line bg-card p-6 shadow-card sm:p-9"><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-teal">Reflection</p><h2 className="display mt-3 text-4xl leading-none">{card.title}</h2><div className="mt-7 space-y-5">{card.questions.map((question) => <label key={question.id} className="block text-sm font-semibold">{question.label}<input aria-label={question.label} className="field mt-2" /></label>)}</div></form>;

  return <label className="flex items-start gap-4 rounded-[1.6rem] border border-dusk/30 bg-ivory p-6 shadow-card sm:p-9"><input type="checkbox" required={card.required} className="mt-1 h-5 w-5 shrink-0" /><span><span className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.17em] text-dusk"><AppIcon name="shield" className="h-4 w-4" />Formal attestation</span><strong className="display mt-4 block text-3xl font-normal leading-tight">{card.statement}</strong><span className="mt-4 block text-sm leading-6 text-ink-soft">{card.consentLabel}</span></span></label>;
}
