import type { Card } from "@/lib/schemas";

export type RichCard = Exclude<Card, { type: "concept" | "example" | "recap" | "quiz_mcq" | "quiz_truefalse" | "quiz_fillblank" }>;

export default function RichBlockCard({ card }: { card: RichCard }) {
  if (card.type === "image") return <div><img src={card.url} alt={card.decorative ? "" : card.altText} className="w-full rounded-2xl border border-line" />{card.caption && <p className="mt-2 text-sm text-ink-soft">{card.caption}</p>}</div>;
  if (card.type === "audio_video") return <div><h2 className="text-xl font-extrabold">{card.title}</h2><a href={card.url} target="_blank" rel="noreferrer" className="mt-3 block rounded-xl bg-primary text-white text-center font-bold py-3">Open media</a>{card.transcript && <div className="mt-4 rounded-xl bg-paper border border-line p-4"><h3 className="font-bold">Transcript</h3><p className="mt-2 whitespace-pre-wrap">{card.transcript}</p></div>}{card.captions && !card.transcript && <p className="mt-4 whitespace-pre-wrap">{card.captions}</p>}</div>;
  if (card.type === "story") return <div><span className="text-xs font-bold uppercase text-primary-deep">Story</span><h2 className="text-xl font-extrabold mt-3">{card.title}</h2><p className="mt-3 whitespace-pre-wrap leading-relaxed">{card.body}</p></div>;
  if (card.type === "flashcard") return <div className="space-y-4"><div className="rounded-2xl bg-card border border-line p-5"><p className="text-xs font-bold text-ink-soft">{card.frontLabel}</p><p className="text-xl font-extrabold mt-2">{card.front}</p></div><details className="rounded-2xl bg-teal/10 border border-teal/30 p-5"><summary className="font-bold cursor-pointer">Reveal {card.backLabel}</summary><p className="mt-3">{card.back}</p></details></div>;
  if (card.type === "scenario") return <div><span className="text-xs font-bold uppercase text-primary-deep">Scenario</span><p className="mt-3 leading-relaxed">{card.context}</p><h2 className="text-xl font-extrabold mt-5">{card.decisionPrompt}</h2>{card.options && <ul className="mt-3 space-y-2">{card.options.map((option) => <li key={option} className="rounded-xl border border-line p-3">{option}</li>)}</ul>}{card.guidance && <details className="mt-4"><summary className="font-bold">Guidance</summary><p className="mt-2">{card.guidance}</p></details>}</div>;
  if (card.type === "practical_task") return <div><span className="text-xs font-bold uppercase text-teal">Practical task</span><h2 className="text-xl font-extrabold mt-3">{card.title}</h2><ol className="mt-4 space-y-3 list-decimal pl-5">{card.instructions.map((step) => <li key={step}>{step}</li>)}</ol><p className="mt-4 rounded-xl bg-paper border border-line p-3"><strong>Alternative:</strong> {card.submissionAlternative}</p></div>;
  if (card.type === "discussion") return <div><span className="text-xs font-bold uppercase text-primary-deep">Discussion</span><h2 className="text-xl font-extrabold mt-3">{card.prompt}</h2><p className="mt-4 rounded-xl bg-paper border border-line p-3"><strong>Private option:</strong> {card.privateAlternative}</p></div>;
  if (card.type === "survey") return <div><h2 className="text-xl font-extrabold">{card.title}</h2><div className="mt-4 space-y-3">{card.questions.map((question) => <label key={question.id} className="block font-semibold">{question.label}<input aria-label={question.label} className="mt-1 w-full rounded-xl border-2 border-line bg-paper px-3 py-2" /></label>)}</div></div>;
  return <label className="flex gap-3 rounded-2xl bg-card border border-line p-5"><input type="checkbox" required={card.required} /><span><strong>Attestation</strong><span className="block mt-1">{card.statement}</span><span className="block text-sm text-ink-soft mt-2">{card.consentLabel}</span></span></label>;
}
