export default function AccessibilityStatementPage() {
  return <article className="px-5 py-10 space-y-6">
    <header><p className="text-sm font-semibold text-primary-deep">BookQuest</p><h1 className="mt-1 text-3xl font-extrabold">Accessibility statement</h1><p className="mt-2 text-sm text-ink-soft">Last updated 13 July 2026</p></header>
    <section className="space-y-2"><h2 className="text-xl font-bold">Our target</h2><p className="text-sm leading-6">BookQuest is being built toward WCAG 2.2 Level AA across course creation, learning, assignment evidence, credential verification and audit reporting. We do not yet claim full conformance: the complete institutional journey has not received its independent manual audit.</p></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">Built-in support</h2><ul className="list-disc pl-5 text-sm leading-6"><li>Keyboard-accessible native controls and visible labels for security and institutional workflows.</li><li>Responsive text-first layouts with status conveyed in words, not color alone.</li><li>Course block validation records accessibility metadata before publication.</li><li>Practical tasks can provide a text submission alternative.</li><li>Audit packs use high-contrast text, repeated headings and readable page structure.</li></ul></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">Known open work</h2><p className="text-sm leading-6">Screen-reader and keyboard testing of the full partner journey, zoom/reflow checks, reduced-motion review, captions/transcripts for future media and remediation of any audit findings remain Phase 3 release gates.</p></section>
    <section className="space-y-2"><h2 className="text-xl font-bold">Remediation process</h2><ol className="list-decimal pl-5 text-sm leading-6"><li>Report the page, task, assistive technology and expected outcome to the organization administrator running the pilot.</li><li>The administrator records impact and provides an accessible alternative for time-sensitive work.</li><li>BookQuest triages blockers first, records the fix or transparent limitation and retests with the affected user.</li><li>Unresolved gaps remain in the release record with an owner and target date; they are not represented as conformant.</li></ol></section>
  </article>;
}

